REPOSITORY_ROOT = '/home/piotr/Documents/auto-changelog-server'
BRANCH_TO_WATCH = 'master'
CHANGELOG_NAME = 'changelog.txt'
COMMIT_MESSAGE = 'Changelog update'
REMOTE_IP_ADDRESS = ''
REMOTE_SECRET = ''
